openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    <опис вашого додатку>
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: <http://localhost:3000>
  - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  /contacts/:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    patch:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    delete:
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
